# Generated by Django 5.0.1 on 2026-01-15 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Raça',
                'verbose_name_plural': 'Raças',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('municipio', models.CharField(max_length=100, verbose_name='Município')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propriedades', to=settings.AUTH_USER_MODEL, verbose_name='Produtor')),
            ],
            options={
                'verbose_name': 'Propriedade',
                'verbose_name_plural': 'Propriedades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Galinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registro', models.CharField(max_length=20, unique=True, verbose_name='Número de Registro')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1, verbose_name='Sexo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('mae', models.ForeignKey(blank=True, limit_choices_to={'sexo': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos_como_mae', to='core.galinha', verbose_name='Mãe')),
                ('pai', models.ForeignKey(blank=True, limit_choices_to={'sexo': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos_como_pai', to='core.galinha', verbose_name='Pai')),
                ('propriedade_atual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='galinhas', to='core.propriedade', verbose_name='Propriedade Atual')),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='galinhas', to='core.raca', verbose_name='Raça')),
            ],
            options={
                'verbose_name': 'Galinha',
                'verbose_name_plural': 'Galinhas',
                'ordering': ['numero_registro'],
            },
        ),
    ]
