# Generated by Django 5.0.1 on 2026-01-15 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaPropriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_processamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Processamento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_destino', to='core.propriedade', verbose_name='Propriedade de Destino')),
                ('galinha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='core.galinha', verbose_name='Galinha')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_origem', to='core.propriedade', verbose_name='Propriedade de Origem')),
            ],
            options={
                'verbose_name': 'Transferência de Propriedade',
                'verbose_name_plural': 'Transferências de Propriedade',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
